services:
  parseable:
    image: parseable/parseable:v0.0.1
    ports:
      - 8000:8000
    networks:
      - parseable_net
    volumes:
      - parseable_db:/data

volumes:
  parseable_db: 

networks:
  parseable_net:
  
